### ISSUE TITLE
Name no longer supported on Chrome

### ISSUE THREAD

**Issue by Intron014** [petar-staynov/BitwardenToChromePasswordConverter#1]
Hi, I tried using it and apparently when importing with the "name" in title and in the whole password list, it just... won't.

I tried to fix it, but my skills as a developer are... kinda null, I'd really appreciate if this could be done, or if not, give me some hints on how could I do it myself. 

Thanks a bunch!

**Comment by pstdevbg** [comment]
I'll look into it.

**Comment by pstdevbg** [comment]
The issue should now be fixed. Sorry for the long delay.
